// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_project_horse_races_db.EntityFramework;

namespace Web_project_horse_races_db.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220510122028_UpdateUserProfileMigration")]
    partial class UpdateUserProfileMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_project_horse_races_db.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("UserId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("UserEmail");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UserName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("UserPassword");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Web_project_horse_races_db.Model.UserBetProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INT")
                        .HasColumnName("UserId");

                    b.Property<int>("BetCount")
                        .HasColumnType("INT")
                        .HasColumnName("UserBetCount");

                    b.Property<int>("LooseBets")
                        .HasColumnType("INT")
                        .HasColumnName("UserLooseBetCount");

                    b.Property<decimal>("MoneyBalance")
                        .HasColumnType("money")
                        .HasColumnName("UserMoneyBalance");

                    b.Property<int>("WinBets")
                        .HasColumnType("INT")
                        .HasColumnName("UserWinBetCount");

                    b.HasKey("UserId");

                    b.ToTable("UsersBetProfiles");
                });

            modelBuilder.Entity("Web_project_horse_races_db.Model.UserBetProfile", b =>
                {
                    b.HasOne("Web_project_horse_races_db.Model.User", "User")
                        .WithOne("UserBetProfile")
                        .HasForeignKey("Web_project_horse_races_db.Model.UserBetProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_project_horse_races_db.Model.User", b =>
                {
                    b.Navigation("UserBetProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
